### ISSUE TITLE
Prices missing

### ISSUE THREAD

**Issue by marcelgcom** [BlueMonday/go-scryfall#11]
The prices strings are empty even though the scryfall's json contains them.

**Comment by BlueMonday** [comment]
I think it might be because of the backwards incompatible change Scryfall made: 

> On April 1, 2019, Scryfall will be removing the usd, eur, and tix fields from API Card objects. You should use the new prices[usd], prices[usd_foil], prices[eur], and prices[tix] properties instead.

Source: https://scryfall.com/blog/category/api

Should be an easy fix.

**Comment by BlueMonday** [comment]
Should be fixed. Sorry about that! Thanks for reporting the issue.

**Comment by marcelgcom** [comment]
Thanks for the prompt fix!
