### ISSUE TITLE
unknown time zone

### ISSUE THREAD

**Issue by lexfrei** [BlueMonday/go-scryfall#14]
Unexpected error: `unknown time zone Etc/GMT+8`
ENV: Alpine image, running in Docker, DigidtalOcean
This error appears for some search worlds like 'negate', but it works fine for 'отвергнуть'
 (the Russian name for this card). I can't see any correlation between cards and error, but it happens all the time for the same cards.
Also, all worked for my old code with a simple query generator and JSON unmarshal.
Also, all worked well on a local machine, the error appears only in Docker. Probably related to Alpine minimal env without preinstalled tzdata

My code ([full](https://github.com/lexfrei/SidisiBot/blob/6f6a4642ece7634f8571e5661340841ca6c1c909/sidisilib/sidisilib.go#L63)):
```go
func FuzzInline(text string) {
	ctx := context.Background()

	client, err := scryfall.NewClient()
	if err != nil {
		log.Println("can't create scryfall client:", err)
		return
	}

	result, err := client.SearchCards(ctx, text, scryfall.SearchCardsOptions{Unique: scryfall.UniqueModeCards, IncludeMultilingual: true})
	if err != nil {
		log.Printf("can't fuzz search for \"%s\": %s", text, err)
		return
	}
	<...>
}
```

So, now by log looks like this:
```text
2019/09/29 00:45:31 can't fuzz search for "negate": unknown time zone Etc/GMT+8
2019/09/29 00:45:32 can't fuzz search for "negate": unknown time zone Etc/GMT+8
```

**Comment by BlueMonday** [comment]
I can try to see if I can find a workaround that doesn't require tzdata. If you install the [tzdata](https://pkgs.alpinelinux.org/package/edge/main/x86/tzdata)  package in your alpine image does it work?

```
apk add tzdata
```

**Comment by BlueMonday** [comment]
> This error appears for some search worlds like 'negate', but it works fine for 'отвергнуть'
(the Russian name for this card). I can't see any correlation between cards and error, but it happens all the time for the same cards.

I am not sure but it might be because certain cards don't have the fields which are date types.

**Comment by BlueMonday** [comment]
Hmmm so it seems like the possible solutions are:
* Everyone who uses the library must install the tzdata package if it is not already installed. The downside of this approach is everyone will need to install it.
* Date type fields are converted to be string types and not time.Time types. The downside of this approach is time.Time types have nice methods to compare times.
* The Date type doesn't try to set the time.Time type to ETC/GMT+8 and instead leaves it in UTC. The downside of this approach is that the times coming from the the server are probably not UTC? This might be good enough though?

**Comment by lexfrei** [comment]
>apk add tzdata

yep, this solved my problem, but I don't like this kind of solutions. Extra deps for unused fields doesn't sound good for me.
IMHO, you have to provide the date as is, without tz change.

**Comment by lexfrei** [comment]
Welp, works for me.
~~Please, check the tz calculation, I'm not sure it's -4h from UTC.~~
